### PR TITLE
set/unset all users

### PR DESCRIPTION
**Pull request by marcopiraccini**
...also fixed some issues that avoided it to work properly when installed globally.

### CODE REVIEW

**Comment by mcollina** [comment]
How can we change the default for new users?

**Comment by marcopiraccini** [comment]
@mcollina we have two options:need Auth0 to do that

**Comment by marcopiraccini** [comment]
@mcollina we have two options:
- Having auth0 to do that, [see here](https://auth0.com/docs/manage-users/user-accounts/metadata/manage-metadata-rules) 
- Call the auth0 API when a user is added to squadre. 

However, in both cases, if a FF is for "everyone" should be removed from the code.

**Comment by mcollina** [comment]
Can you please add a link for the first case in the README too?

**Comment by marcopiraccini** [comment]
> Can you please add a link for the first case in the README too?

[Done](https://github.com/platformatic/semaforo/pull/5/commits/8813ea77063b2c811a09c4f984114cb512a9d843)

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
